image: node:12-alpine
cache:
  key: "alpine"
  paths:
    - node_modules/

before_script:
  - npm ci

test:
  script:
    - yarn test
  tags:
    - docker

build:
  stage: build
  artifacts:
    paths:
      - dist/
  script:
    - yarn run build
  only:
    - master
  tags:
    - docker
