const PREFIX = 'User/';

export const SET_PAGE = 'SET_PAGE';

export const SUBMIT_USER_REQUEST = `${PREFIX}SUBMIT_USER_REQUEST`;
export const SUBMIT_USER_SUCCESS = `${PREFIX}SUBMIT_USER_SUCCESS`;
export const SUBMIT_USER_ERROR = `${PREFIX}SUBMIT_USER_ERROR`;

export const GET_USERS_REQUEST = `${PREFIX}GET_USERS_REQUEST`;
export const GET_USERS_SUCCESS = `${PREFIX}GET_USERS_SUCCESS`;
export const GET_USERS_ERROR = `${PREFIX}GET_USERS_ERROR`;

export const GET_USER_REQUEST = `${PREFIX}GET_USER_REQUEST`;
export const GET_USER_SUCCESS = `${PREFIX}GET_USER_SUCCESS`;
export const GET_USER_ERROR = `${PREFIX}GET_USER_ERROR`;
export const RESET_USER = `${PREFIX}RESET_USER`;

export const GET_USERS_BY_STATE_AND_ROLE_REQUEST = `${PREFIX}GET_USERS_BY_STATE_AND_ROLE_REQUEST`;
export const GET_USERS_BY_STATE_AND_ROLE_SUCCESS = `${PREFIX}GET_USERS_BY_STATE_AND_ROLE_SUCCESS`;
export const GET_USERS_BY_STATE_AND_ROLE_ERROR = `${PREFIX}GET_USERS_BY_STATE_AND_ROLE_ERROR`;

export const DELETE_USER_REQUEST = `${PREFIX}DELETE_USER_REQUEST`;
export const DELETE_USER_SUCCESS = `${PREFIX}DELETE_USER_SUCCESS`;
export const DELETE_USER_ERROR = `${PREFIX}DELETE_USER_ERROR`;

export const SUBMIT_PASSWORD_RECOVERY_REQUESTED = 'SUBMIT_PASSWORD_RECOVERY_REQUESTED';
