const PREFIX = 'Common/';

export const ERROR_OCCURRED = `${PREFIX}ERROR_OCCURRED`;

export const SET_NOTIFICATION = `${PREFIX}SET_NOTIFICATION`;

export const RESET_NOTIFICATION = `${PREFIX}RESET_NOTIFICATION`;

export const SET_SEARCH_PARAMS = `${PREFIX}SET_SEARCH_PARAMS`;
export const RESET_SEARCH_PARAMS = `${PREFIX}RESET_SEARCH_PARAMS`;

export const OPEN_CONFIRM_MODAL = `${PREFIX}OPEN_CONFIRM_MODAL`;

export const CLOSE_CONFIRM_MODAL = `${PREFIX}CLOSE_CONFIRM_MODAL`;
