const PREFIX = 'Types/';

export const GET_UPS_DROPDOWN_REQUEST = `${PREFIX}GET_UPS_DROPDOWN_REQUEST`;
export const GET_UPS_DROPDOWN_SUCCESS = `${PREFIX}GET_UPS_DROPDOWN_SUCCESS`;
export const GET_UPS_DROPDOWN_ERROR = `${PREFIX}GET_UPS_DROPDOWN_ERROR`;

export const GET_AREAS_DROPDOWN_REQUEST = `${PREFIX}GET_AREAS_DROPDOWN_REQUEST`;
export const GET_AREAS_DROPDOWN_SUCCESS = `${PREFIX}GET_AREAS_DROPDOWN_SUCCESS`;
export const GET_AREAS_DROPDOWN_ERROR = `${PREFIX}GET_AREAS_DROPDOWN_ERROR`;

export const GET_SEGMENTS_DROPDOWN_REQUEST = `${PREFIX}GET_SEGMENTS_DROPDOWN_REQUEST`;
export const GET_SEGMENTS_DROPDOWN_SUCCESS = `${PREFIX}GET_SEGMENTS_DROPDOWN_SUCCESS`;
export const GET_SEGMENTS_DROPDOWN_ERROR = `${PREFIX}GET_SEGMENTS_DROPDOWN_ERROR`;

export const GET_FILES_REQUEST = `${PREFIX}GET_FILES_REQUEST`;
export const GET_FILES_SUCCESS = `${PREFIX}GET_FILES_SUCCESS`;
export const GET_FILES_ERROR = `${PREFIX}GET_FILES_ERROR`;

export const GET_STATUSES_REQUEST = `${PREFIX}GET_STATUSES_REQUEST`;
export const GET_STATUSES_SUCCESS = `${PREFIX}GET_STATUSES_SUCCESS`;
export const GET_STATUSES_ERROR = `${PREFIX}GET_STATUSES_ERROR`;

export const GET_SITUATIONS_REQUEST = `${PREFIX}GET_SITUATIONS_REQUEST`;
export const GET_SITUATIONS_SUCCESS = `${PREFIX}GET_SITUATIONS_SUCCESS`;
export const GET_SITUATIONS_ERROR = `${PREFIX}GET_SITUATIONS_ERROR`;

export const GET_ASSIGNMENTS_TYPES_REQUEST = `${PREFIX}GET_ASSIGNMENTS_TYPES_REQUEST`;
export const GET_ASSIGNMENTS_TYPES_SUCCESS = `${PREFIX}GET_ASSIGNMENTS_TYPES_SUCCESS`;
export const GET_ASSIGNMENTS_TYPES_ERROR = `${PREFIX}GET_ASSIGNMENTS_TYPES_ERROR`;
