const PREFIX = 'Review/';

export const GET_SURVEYS_REQUEST = `${PREFIX}GET_SURVEYS_REQUEST`;
export const GET_SURVEYS_SUCCESS = `${PREFIX}GET_SURVEYS_SUCCESS`;
export const GET_SURVEYS_ERROR = `${PREFIX}GET_SURVEYS_ERROR`;

export const GET_SURVEY_REQUEST = `${PREFIX}GET_SURVEY_REQUEST`;
export const GET_SURVEY_SUCCESS = `${PREFIX}GET_SURVEY_SUCCESS`;
export const GET_SURVEY_ERROR = `${PREFIX}GET_SURVEY_ERROR`;

export const GET_ADDRESS_REQUEST = `${PREFIX}GET_ADDRESS_REQUEST`;
export const GET_ADDRESS_SUCCESS = `${PREFIX}GET_ADDRESS_SUCCESS`;
export const GET_ADDRESS_ERROR = `${PREFIX}GET_ADDRESS_ERROR`;

export const FINISH_SURVEY_REQUEST = `${PREFIX}FINISH_SURVEY_REQUEST`;
export const FINISH_SURVEY_SUCCESS = `${PREFIX}FINISH_SURVEY_SUCCESS`;
export const FINISH_SURVEY_ERROR = `${PREFIX}FINISH_SURVEY_ERROR`;

export const REASSIGN_SURVEY_REQUEST = `${PREFIX}REASSIGN_SURVEY_REQUEST`;
export const REASSIGN_SURVEY_SUCCESS = `${PREFIX}REASSIGN_SURVEY_SUCCESS`;
export const REASSIGN_SURVEY_ERROR = `${PREFIX}REASSIGN_SURVEY_ERROR`;

export const APPROVE_SURVEY_REQUEST = `${PREFIX}APPROVE_SURVEY_REQUEST`;
export const APPROVE_SURVEY_SUCCESS = `${PREFIX}APPROVE_SURVEY_SUCCESS`;
export const APPROVE_SURVEY_ERROR = `${PREFIX}APPROVE_SURVEY_ERROR`;

export const REOPEN_SURVEY_REQUEST = `${PREFIX}REOPEN_SURVEY_REQUEST`;
export const REOPEN_SURVEY_SUCCESS = `${PREFIX}REOPEN_SURVEY_SUCCESS`;
export const REOPEN_SURVEY_ERROR = `${PREFIX}REOPEN_SURVEY_ERROR`;

export const SUPERVISE_SURVEY_REQUEST = `${PREFIX}SUPERVISE_SURVEY_REQUEST`;
export const SUPERVISE_SURVEY_SUCCESS = `${PREFIX}SUPERVISE_SURVEY_SUCCESS`;
export const SUPERVISE_SURVEY_ERROR = `${PREFIX}SUPERVISE_SURVEY_ERROR`;

export const RECOVER_SURVEY_REQUEST = `${PREFIX}RECOVER_SURVEY_REQUEST`;
export const RECOVER_SURVEY_SUCCESS = `${PREFIX}RECOVER_SURVEY_SUCCESS`;
export const RECOVER_SURVEY_ERROR = `${PREFIX}RECOVER_SURVEY_ERROR`;
