const PREFIX = 'Session/';

export const GET_SESSION_USER_REQUEST = `${PREFIX}GET_SESSION_USER_REQUEST`;
export const GET_SESSION_USER_SUCCESS = `${PREFIX}GET_SESSION_USER_SUCCESS`;
export const GET_SESSION_USER_ERROR = `${PREFIX}GET_SESSION_USER_ERROR`;

export const SIGN_OUT_REQUESTED = `${PREFIX}SIGN_OUT_REQUESTED`;

export const VALIDATE_SESSION = `${PREFIX}VALIDATE_SESSION`;
export const VALIDATE_SESSION_SUCCESS = `${PREFIX}VALIDATE_SESSION_SUCCESS`;
export const VALIDATE_SESSION_ERROR = `${PREFIX}VALIDATE_SESSION_ERROR`;
