const PREFIX = 'Assignment/';

export const GET_ASSIGNMENTS_REQUEST = `${PREFIX}GET_ASSIGNMENTS_REQUEST`;
export const GET_ASSIGNMENTS_SUCCESS = `${PREFIX}GET_ASSIGNMENTS_SUCCESS`;
export const GET_ASSIGNMENTS_ERROR = `${PREFIX}GET_ASSIGNMENTS_ERROR`;
export const UPDATE_ASSIGNMENT = `${PREFIX}UPDATE_ASSIGNMENT`;
export const UNSET_TO_ASSIGN = `${PREFIX}UNSET_TO_ASSIGN`;

export const UPDATE_ASSIGNMENTS_REQUEST = `${PREFIX}UPDATE_ASSIGNMENTS_REQUEST`;
export const UPDATE_ASSIGNMENTS_SUCCESS = `${PREFIX}UPDATE_ASSIGNMENTS_SUCCESS`;
export const UPDATE_ASSIGNMENTS_ERROR = `${PREFIX}UPDATE_ASSIGNMENTS_ERROR`;
