const PREFIX = 'StaticData/';

export const GET_STATIC_DATA_REQUEST = `${PREFIX}GET_STATIC_DATA_REQUEST`;
export const GET_STATIC_DATA_SUCCESS = `${PREFIX}GET_STATIC_DATA_SUCCESS`;
export const GET_STATIC_DATA_ERROR = `${PREFIX}GET_STATIC_DATA_ERROR`;
