const PREFIX = 'FieldMaterials/';

export const GET_FIELD_MATERIALS_REQUEST = `${PREFIX}GET_FIELD_MATERIALS_REQUEST`;
export const GET_FIELD_MATERIALS_SUCCESS = `${PREFIX}GET_FIELD_MATERIALS_SUCCESS`;
export const GET_FIELD_MATERIALS_ERROR = `${PREFIX}GET_FIELD_MATERIALS_ERROR`;

export const GET_FIELD_MATERIALS_BY_STATE_REQUEST = `${PREFIX}GET_FIELD_MATERIALS_BY_STATE_REQUEST`;
export const GET_FIELD_MATERIALS_BY_STATE_SUCCESS = `${PREFIX}GET_FIELD_MATERIALS_BY_STATE_SUCCESS`;
export const GET_FIELD_MATERIALS_BY_STATE_ERROR = `${PREFIX}GET_FIELD_MATERIALS_BY_STATE_ERROR`;

export const GET_FIELD_MATERIALS_BY_UPS_REQUEST = `${PREFIX}GET_FIELD_MATERIALS_BY_UPS_REQUEST`;
export const GET_FIELD_MATERIALS_BY_UPS_SUCCESS = `${PREFIX}GET_FIELD_MATERIALS_BY_UPS_SUCCESS`;
export const GET_FIELD_MATERIALS_BY_UPS_ERROR = `${PREFIX}GET_FIELD_MATERIALS_BY_UPS_ERROR`;

export const GET_FIELD_MATERIALS_BY_AREA_REQUEST = `${PREFIX}GET_FIELD_MATERIALS_BY_AREA_REQUEST`;
export const GET_FIELD_MATERIALS_BY_AREA_SUCCESS = `${PREFIX}GET_FIELD_MATERIALS_BY_AREA_SUCCESS`;
export const GET_FIELD_MATERIALS_BY_AREA_ERROR = `${PREFIX}GET_FIELD_MATERIALS_BY_AREA_ERROR`;
